/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatcliente.IU;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlphaLegends
 */
public class IUConverchation extends javax.swing.JFrame {
    static int port = 9999;
    private String receiver;
    static DatagramSocket clientSocket;
    String ConverChat;
    static boolean go = false;
    /**
     * Creates new form IUConverchation
     */
    public IUConverchation(DatagramSocket clientSocket) {
        initComponents();
        this.clientSocket = clientSocket;
        this.ConverChat = "";
    }
    
    public IUConverchation() {
        initComponents();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListOnline = new javax.swing.JTable();
        Info = new javax.swing.JTextField();
        Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Chat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        ListOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nick"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListOnlineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListOnline);

        Info.setEditable(false);

        jLabel3.setText("Chat");

        Chat.setEditable(false);
        Chat.setColumns(20);
        Chat.setRows(5);
        jScrollPane2.setViewportView(Chat);

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane3.setViewportView(Text);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Online");

        jLabel2.setText("Informação");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Criar um grupo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(476, 476, 476))
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListOnlineMouseClicked
        int linha = ListOnline.getSelectedRow();
        receiver =  (String) (ListOnline.getValueAt(linha,0)); 

    }//GEN-LAST:event_ListOnlineMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        go = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        byte[] sendData = new byte[1024];
        InetAddress IPAddress = null;
        try {
            IPAddress = InetAddress.getByName("localhost");
        } catch (UnknownHostException ex) {
            Logger.getLogger(IUConverchation.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sentence = "19\n"; //deslogar
        sendData = sentence.getBytes();
        DatagramPacket sendPacket = new DatagramPacket(sendData,sendData.length,IPAddress,port);
        try {
            clientSocket.send(sendPacket);
        } catch (IOException ex) {
            Logger.getLogger(IUConverchation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clientSocket.close();
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        byte[] sendData = new byte[1024];
        InetAddress IPAddress = null;
        try {
            IPAddress = InetAddress.getByName("localhost");
        } catch (UnknownHostException ex) {
            Logger.getLogger(IUConverchation.class.getName()).log(Level.SEVERE, null, ex);
        }
        String name = JOptionPane.showInputDialog("Insira um nome para o grupo");
        String members = JOptionPane.showInputDialog("Insira o nick dos membros","acrescente ; entre o nick dos membros");
        String sentence = "14\n"; //criar grupo
        sentence += name+"\n";
        sentence += members+"\n";
        sendData = sentence.getBytes();
        DatagramPacket sendPacket = new DatagramPacket(sendData,sendData.length,IPAddress,port);// numero da porta 9999, pode ser alterada
        try {
            clientSocket.send(sendPacket);
        } catch (IOException ex) {
            Logger.getLogger(IUConverchation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void tratarMensagem(DatagramPacket receivePacket){
        String sentence = new String(receivePacket.getData());
        String nicks[];
        switch(sentence.charAt(0)){
            case '2':
                if(sentence.charAt(1) == '1'){
                plotarChatGeral(sentence);   
                }else{
                plotarChat(sentence);
                }
                break;
            case'1'://atualizacao de onlines
                if(sentence.charAt(1) == '2'){//exibir no infoOnline
                    nicks = sentence.split("\n");
                    infoOnline(nicks);
                }
                if(sentence.charAt(1) == '3'){//exibir todos na tabela
                    nicks = sentence.split("\n");

                    plotarOnline(nicks);
                }if(sentence.charAt(1) == '8'){//exibir no infoOnline
                    nicks = sentence.split("\n");
                    Info.setText(nicks[1]+" esta offline");  
                }
                break;
                    
        }
    }
    
    public void infoOnline(String[] nicks){
        Info.setText(nicks[1]+" esta online");
    }
    
    public void plotarOnline(String[] nicks){
        DefaultTableModel model = (DefaultTableModel) ListOnline.getModel();//impressao dos resultados na tabela
            model.setNumRows(0);
            for(int i=1;i<nicks.length;i++){
                Object[] linha = new Object[1];
                linha[0] = nicks[i];
                model.addRow(linha);
        }
    }
    
    public void plotarChat(String sentence){
        String message[] = sentence.split("\n");
        if(message.length>=2){
        ConverChat += "["+message[2]+ "]: ";
        for(int i=3;i<message.length;i++){
            ConverChat+= message[i];
        }
        ConverChat+="\n";
        Chat.setText(ConverChat);
        }
    }
    
    public void plotarChatGeral(String sentence){
        String message[] = sentence.split("\n");
        if(message.length>=2){
        ConverChat += "[ChatGeral]: ";
        ConverChat += "["+message[2]+ "]: ";
        for(int i=3;i<message.length;i++){
            ConverChat+= message[i];
        }
        ConverChat+="\n";
        Chat.setText(ConverChat);  
        }
    }
            
    public void sendMessage(DatagramSocket clientSocket)throws IOException {

        if(go){
            this.clientSocket = clientSocket;
            byte[] sendData = new byte[1024*1024];
            String msg = "";
            InetAddress IPAddress = InetAddress.getByName("localhost");
            
            if(receiver == null)JOptionPane.showMessageDialog(null,"Escolha para quem será a mensagem no lista de usuarios");
            else{
                if(!receiver.equals("ChatGeral")){
                    msg = "20\n"; //mensagem privada
                    msg += receiver+"\n";
                    msg += getTitle()+"\n";
                    msg += Text.getText();
                    sendData = msg.getBytes();
                    DatagramPacket sendPacket = new DatagramPacket(sendData,sendData.length,IPAddress,port);// numero da porta 9999, pode ser alterada
                    clientSocket.send(sendPacket);
                    
                    
                    String message[] = msg.split("\n");
                    ConverChat += "["+ getTitle() + "] to ["+receiver+"]: ";
                    for(int i=3;i<message.length;i++){
                        ConverChat+= message[i];
                    }
                    ConverChat+="\n";
                    Chat.setText(ConverChat);   
                    

                }else{
                    msg = "21\n"; //mensagem no chat geral
                    msg += receiver+"\n";
                    msg += getTitle()+"\n";
                    msg += Text.getText();
                    sendData = msg.getBytes();
                    DatagramPacket sendPacket = new DatagramPacket(sendData,sendData.length,IPAddress,port);// numero da porta 9999, pode ser alterada
                    clientSocket.send(sendPacket);
                }
                Text.setText("");
                
            }
            go = false;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUConverchation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUConverchation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUConverchation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUConverchation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUConverchation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Chat;
    private javax.swing.JTextField Info;
    private javax.swing.JTable ListOnline;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextArea Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    
}
